2024-07-26 20:39:05,386 INFO    StreamThr :27472 [internal.py:wandb_internal():86] W&B internal server running at pid: 27472, started at: 2024-07-26 20:39:05.385800
2024-07-26 20:39:05,387 DEBUG   HandlerThread:27472 [handler.py:handle_request():146] handle_request: status
2024-07-26 20:39:05,388 INFO    WriterThread:27472 [datastore.py:open_for_write():87] open: c:\Users\lenovo\Desktop\CUHK\Research\wandb\run-20240726_203859-g677k1a8\run-g677k1a8.wandb
2024-07-26 20:39:05,389 DEBUG   SenderThread:27472 [sender.py:send():379] send: header
2024-07-26 20:39:05,389 DEBUG   SenderThread:27472 [sender.py:send():379] send: run
2024-07-26 20:39:06,975 INFO    SenderThread:27472 [dir_watcher.py:__init__():211] watching files in: c:\Users\lenovo\Desktop\CUHK\Research\wandb\run-20240726_203859-g677k1a8\files
2024-07-26 20:39:06,975 INFO    SenderThread:27472 [sender.py:_start_run_threads():1124] run started: g677k1a8 with start time 1721997544.980709
2024-07-26 20:39:06,992 DEBUG   HandlerThread:27472 [handler.py:handle_request():146] handle_request: check_version
2024-07-26 20:39:06,992 DEBUG   SenderThread:27472 [sender.py:send_request():406] send_request: check_version
2024-07-26 20:39:07,047 DEBUG   HandlerThread:27472 [handler.py:handle_request():146] handle_request: run_start
2024-07-26 20:39:07,061 DEBUG   HandlerThread:27472 [system_info.py:__init__():26] System info init
2024-07-26 20:39:07,061 DEBUG   HandlerThread:27472 [system_info.py:__init__():41] System info init done
2024-07-26 20:39:07,061 INFO    HandlerThread:27472 [system_monitor.py:start():194] Starting system monitor
2024-07-26 20:39:07,062 INFO    SystemMonitor:27472 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-07-26 20:39:07,062 INFO    HandlerThread:27472 [system_monitor.py:probe():214] Collecting system info
2024-07-26 20:39:07,072 INFO    SystemMonitor:27472 [interfaces.py:start():190] Started cpu monitoring
2024-07-26 20:39:07,073 INFO    SystemMonitor:27472 [interfaces.py:start():190] Started disk monitoring
2024-07-26 20:39:07,074 INFO    SystemMonitor:27472 [interfaces.py:start():190] Started gpu monitoring
2024-07-26 20:39:07,074 INFO    SystemMonitor:27472 [interfaces.py:start():190] Started memory monitoring
2024-07-26 20:39:07,092 INFO    SystemMonitor:27472 [interfaces.py:start():190] Started network monitoring
2024-07-26 20:39:07,092 DEBUG   HandlerThread:27472 [system_info.py:probe():150] Probing system
2024-07-26 20:39:07,095 DEBUG   HandlerThread:27472 [gitlib.py:_init_repo():56] git repository is invalid
2024-07-26 20:39:07,095 DEBUG   HandlerThread:27472 [system_info.py:probe():198] Probing system done
2024-07-26 20:39:07,095 DEBUG   HandlerThread:27472 [system_monitor.py:probe():223] {'os': 'Windows-10-10.0.19045-SP0', 'python': '3.9.19', 'heartbeatAt': '2024-07-26T12:39:07.092736', 'startedAt': '2024-07-26T12:38:59.815910', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': '<python with no main file>', 'codePathLocal': None, 'host': 'LAPTOP-7II9UK57', 'username': 'lenovo', 'executable': 'c:\\Users\\lenovo\\anaconda3\\envs\\dl\\python.exe', 'cpu_count': 8, 'cpu_count_logical': 16, 'cpu_freq': {'current': 3201.0, 'min': 0.0, 'max': 3201.0}, 'cpu_freq_per_core': [{'current': 3201.0, 'min': 0.0, 'max': 3201.0}], 'disk': {'/': {'total': 475.69237899780273, 'used': 345.3506660461426}}, 'gpu': 'NVIDIA GeForce GTX 1650', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce GTX 1650', 'memory_total': 4294967296}], 'memory': {'total': 13.855525970458984}}
2024-07-26 20:39:07,096 INFO    HandlerThread:27472 [system_monitor.py:probe():224] Finished collecting system info
2024-07-26 20:39:07,096 INFO    HandlerThread:27472 [system_monitor.py:probe():227] Publishing system info
2024-07-26 20:39:07,096 DEBUG   HandlerThread:27472 [system_info.py:_save_conda():207] Saving list of conda packages installed into the current environment
2024-07-26 20:39:07,101 ERROR   gpu       :27472 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-07-26 20:39:07,326 DEBUG   HandlerThread:27472 [handler.py:handle_request():146] handle_request: status_report
2024-07-26 20:39:07,482 DEBUG   HandlerThread:27472 [handler.py:handle_request():146] handle_request: status_report
2024-07-26 20:39:07,987 INFO    Thread-298:27472 [dir_watcher.py:_on_file_created():271] file/dir created: c:\Users\lenovo\Desktop\CUHK\Research\wandb\run-20240726_203859-g677k1a8\files\conda-environment.yaml
2024-07-26 20:39:09,121 ERROR   gpu       :27472 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-07-26 20:39:11,141 ERROR   gpu       :27472 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-07-26 20:39:12,379 DEBUG   HandlerThread:27472 [handler.py:handle_request():146] handle_request: status_report
2024-07-26 20:39:12,539 DEBUG   HandlerThread:27472 [handler.py:handle_request():146] handle_request: status_report
2024-07-26 20:39:13,191 ERROR   gpu       :27472 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-07-26 20:39:15,048 INFO    Thread-298:27472 [dir_watcher.py:_on_file_modified():288] file/dir modified: c:\Users\lenovo\Desktop\CUHK\Research\wandb\run-20240726_203859-g677k1a8\files\conda-environment.yaml
2024-07-26 20:39:15,073 DEBUG   HandlerThread:27472 [system_info.py:_save_conda():222] Saving conda packages done
2024-07-26 20:39:15,074 INFO    HandlerThread:27472 [system_monitor.py:probe():229] Finished publishing system info
2024-07-26 20:39:15,074 DEBUG   HandlerThread:27472 [handler.py:handle_request():146] handle_request: status_report
2024-07-26 20:39:15,074 DEBUG   HandlerThread:27472 [handler.py:handle_request():146] handle_request: keepalive
2024-07-26 20:39:15,075 DEBUG   SenderThread:27472 [sender.py:send():379] send: files
2024-07-26 20:39:15,075 INFO    SenderThread:27472 [sender.py:_save_file():1390] saving file wandb-metadata.json with policy now
2024-07-26 20:39:15,224 ERROR   gpu       :27472 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-07-26 20:39:15,323 DEBUG   HandlerThread:27472 [handler.py:handle_request():146] handle_request: python_packages
2024-07-26 20:39:15,323 DEBUG   SenderThread:27472 [sender.py:send_request():406] send_request: python_packages
2024-07-26 20:39:15,323 DEBUG   HandlerThread:27472 [handler.py:handle_request():146] handle_request: stop_status
2024-07-26 20:39:15,324 DEBUG   SenderThread:27472 [sender.py:send_request():406] send_request: stop_status
2024-07-26 20:39:15,327 DEBUG   HandlerThread:27472 [handler.py:handle_request():146] handle_request: internal_messages
2024-07-26 20:39:15,605 DEBUG   SenderThread:27472 [sender.py:send():379] send: telemetry
2024-07-26 20:39:15,769 INFO    wandb-upload_0:27472 [upload_job.py:push():131] Uploaded file C:\Users\lenovo\AppData\Local\Temp\tmp1m1oyty0wandb\0lliyy1k-wandb-metadata.json
2024-07-26 20:39:16,060 INFO    Thread-298:27472 [dir_watcher.py:_on_file_created():271] file/dir created: c:\Users\lenovo\Desktop\CUHK\Research\wandb\run-20240726_203859-g677k1a8\files\wandb-metadata.json
2024-07-26 20:39:16,060 INFO    Thread-298:27472 [dir_watcher.py:_on_file_created():271] file/dir created: c:\Users\lenovo\Desktop\CUHK\Research\wandb\run-20240726_203859-g677k1a8\files\requirements.txt
2024-07-26 20:39:16,621 DEBUG   HandlerThread:27472 [handler.py:handle_request():146] handle_request: status_report
2024-07-26 20:39:17,249 ERROR   gpu       :27472 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-07-26 20:39:17,429 DEBUG   HandlerThread:27472 [handler.py:handle_request():146] handle_request: status_report
2024-07-26 20:39:17,587 DEBUG   HandlerThread:27472 [handler.py:handle_request():146] handle_request: status_report
2024-07-26 20:39:19,265 ERROR   gpu       :27472 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-07-26 20:39:21,281 ERROR   gpu       :27472 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-07-26 20:39:21,662 DEBUG   HandlerThread:27472 [handler.py:handle_request():146] handle_request: status_report
2024-07-26 20:39:22,462 DEBUG   HandlerThread:27472 [handler.py:handle_request():146] handle_request: status_report
2024-07-26 20:39:22,622 DEBUG   HandlerThread:27472 [handler.py:handle_request():146] handle_request: status_report
2024-07-26 20:39:23,291 ERROR   gpu       :27472 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-07-26 20:39:25,313 ERROR   gpu       :27472 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-07-26 20:39:26,704 DEBUG   HandlerThread:27472 [handler.py:handle_request():146] handle_request: status_report
2024-07-26 20:39:27,334 ERROR   gpu       :27472 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-07-26 20:39:27,500 DEBUG   HandlerThread:27472 [handler.py:handle_request():146] handle_request: status_report
2024-07-26 20:39:27,659 DEBUG   HandlerThread:27472 [handler.py:handle_request():146] handle_request: status_report
2024-07-26 20:39:29,355 ERROR   gpu       :27472 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-07-26 20:39:30,317 DEBUG   HandlerThread:27472 [handler.py:handle_request():146] handle_request: internal_messages
2024-07-26 20:39:30,333 DEBUG   HandlerThread:27472 [handler.py:handle_request():146] handle_request: stop_status
2024-07-26 20:39:30,334 DEBUG   SenderThread:27472 [sender.py:send_request():406] send_request: stop_status
2024-07-26 20:39:31,373 ERROR   gpu       :27472 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-07-26 20:39:32,525 DEBUG   HandlerThread:27472 [handler.py:handle_request():146] handle_request: status_report
2024-07-26 20:39:32,573 DEBUG   HandlerThread:27472 [handler.py:handle_request():146] handle_request: status_report
2024-07-26 20:39:32,683 DEBUG   HandlerThread:27472 [handler.py:handle_request():146] handle_request: status_report
2024-07-26 20:39:33,391 ERROR   gpu       :27472 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-07-26 20:39:35,418 ERROR   gpu       :27472 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-07-26 20:39:37,492 ERROR   gpu       :27472 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-07-26 20:39:37,562 DEBUG   HandlerThread:27472 [handler.py:handle_request():146] handle_request: status_report
2024-07-26 20:39:37,597 DEBUG   HandlerThread:27472 [handler.py:handle_request():146] handle_request: status_report
2024-07-26 20:39:37,705 DEBUG   HandlerThread:27472 [handler.py:handle_request():146] handle_request: status_report
2024-07-26 20:39:38,186 INFO    Thread-298:27472 [dir_watcher.py:_on_file_modified():288] file/dir modified: c:\Users\lenovo\Desktop\CUHK\Research\wandb\run-20240726_203859-g677k1a8\files\config.yaml
2024-07-26 20:39:39,504 ERROR   gpu       :27472 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-07-26 20:39:41,527 ERROR   gpu       :27472 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-07-26 20:39:42,595 DEBUG   HandlerThread:27472 [handler.py:handle_request():146] handle_request: status_report
2024-07-26 20:39:42,737 DEBUG   HandlerThread:27472 [handler.py:handle_request():146] handle_request: status_report
2024-07-26 20:39:42,832 DEBUG   HandlerThread:27472 [handler.py:handle_request():146] handle_request: status_report
2024-07-26 20:39:43,544 ERROR   gpu       :27472 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-07-26 20:39:44,240 INFO    Thread-298:27472 [dir_watcher.py:_on_file_created():271] file/dir created: c:\Users\lenovo\Desktop\CUHK\Research\wandb\run-20240726_203859-g677k1a8\files\output.log
2024-07-26 20:39:45,330 DEBUG   HandlerThread:27472 [handler.py:handle_request():146] handle_request: internal_messages
2024-07-26 20:39:45,346 DEBUG   HandlerThread:27472 [handler.py:handle_request():146] handle_request: stop_status
2024-07-26 20:39:45,346 DEBUG   SenderThread:27472 [sender.py:send_request():406] send_request: stop_status
2024-07-26 20:39:45,560 ERROR   gpu       :27472 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-07-26 20:39:46,264 INFO    Thread-298:27472 [dir_watcher.py:_on_file_modified():288] file/dir modified: c:\Users\lenovo\Desktop\CUHK\Research\wandb\run-20240726_203859-g677k1a8\files\output.log
2024-07-26 20:39:46,867 DEBUG   SenderThread:27472 [sender.py:send():379] send: telemetry
2024-07-26 20:39:46,868 DEBUG   SenderThread:27472 [sender.py:send():379] send: exit
2024-07-26 20:39:46,869 INFO    SenderThread:27472 [sender.py:send_exit():586] handling exit code: 0
2024-07-26 20:39:46,869 INFO    SenderThread:27472 [sender.py:send_exit():588] handling runtime: 39
2024-07-26 20:39:46,869 INFO    SenderThread:27472 [sender.py:_save_file():1390] saving file wandb-summary.json with policy end
2024-07-26 20:39:46,870 INFO    SenderThread:27472 [sender.py:send_exit():594] send defer
2024-07-26 20:39:46,870 DEBUG   HandlerThread:27472 [handler.py:handle_request():146] handle_request: defer
2024-07-26 20:39:46,870 INFO    HandlerThread:27472 [handler.py:handle_request_defer():172] handle defer: 0
2024-07-26 20:39:46,870 DEBUG   SenderThread:27472 [sender.py:send_request():406] send_request: defer
2024-07-26 20:39:46,871 INFO    SenderThread:27472 [sender.py:send_request_defer():610] handle sender defer: 0
2024-07-26 20:39:46,871 INFO    SenderThread:27472 [sender.py:transition_state():614] send defer: 1
2024-07-26 20:39:46,871 DEBUG   HandlerThread:27472 [handler.py:handle_request():146] handle_request: defer
2024-07-26 20:39:46,871 INFO    HandlerThread:27472 [handler.py:handle_request_defer():172] handle defer: 1
2024-07-26 20:39:46,871 DEBUG   SenderThread:27472 [sender.py:send_request():406] send_request: defer
2024-07-26 20:39:46,871 INFO    SenderThread:27472 [sender.py:send_request_defer():610] handle sender defer: 1
2024-07-26 20:39:46,871 INFO    SenderThread:27472 [sender.py:transition_state():614] send defer: 2
2024-07-26 20:39:46,871 DEBUG   HandlerThread:27472 [handler.py:handle_request():146] handle_request: defer
2024-07-26 20:39:46,871 INFO    HandlerThread:27472 [handler.py:handle_request_defer():172] handle defer: 2
2024-07-26 20:39:46,871 INFO    HandlerThread:27472 [system_monitor.py:finish():203] Stopping system monitor
2024-07-26 20:39:46,872 DEBUG   SystemMonitor:27472 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-07-26 20:39:46,872 INFO    HandlerThread:27472 [interfaces.py:finish():202] Joined cpu monitor
2024-07-26 20:39:46,885 DEBUG   SystemMonitor:27472 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-07-26 20:39:46,885 INFO    HandlerThread:27472 [interfaces.py:finish():202] Joined disk monitor
2024-07-26 20:39:46,885 DEBUG   SystemMonitor:27472 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-07-26 20:39:46,958 INFO    HandlerThread:27472 [interfaces.py:finish():202] Joined gpu monitor
2024-07-26 20:39:46,959 INFO    HandlerThread:27472 [interfaces.py:finish():202] Joined memory monitor
2024-07-26 20:39:46,959 INFO    HandlerThread:27472 [interfaces.py:finish():202] Joined network monitor
2024-07-26 20:39:46,959 DEBUG   SenderThread:27472 [sender.py:send_request():406] send_request: defer
2024-07-26 20:39:46,960 INFO    SenderThread:27472 [sender.py:send_request_defer():610] handle sender defer: 2
2024-07-26 20:39:46,960 INFO    SenderThread:27472 [sender.py:transition_state():614] send defer: 3
2024-07-26 20:39:46,960 DEBUG   SenderThread:27472 [sender.py:send():379] send: stats
2024-07-26 20:39:46,960 DEBUG   HandlerThread:27472 [handler.py:handle_request():146] handle_request: defer
2024-07-26 20:39:46,960 INFO    HandlerThread:27472 [handler.py:handle_request_defer():172] handle defer: 3
2024-07-26 20:39:46,961 DEBUG   SenderThread:27472 [sender.py:send_request():406] send_request: defer
2024-07-26 20:39:46,961 INFO    SenderThread:27472 [sender.py:send_request_defer():610] handle sender defer: 3
2024-07-26 20:39:46,961 INFO    SenderThread:27472 [sender.py:transition_state():614] send defer: 4
2024-07-26 20:39:46,961 DEBUG   HandlerThread:27472 [handler.py:handle_request():146] handle_request: defer
2024-07-26 20:39:46,961 INFO    HandlerThread:27472 [handler.py:handle_request_defer():172] handle defer: 4
2024-07-26 20:39:46,962 DEBUG   SenderThread:27472 [sender.py:send_request():406] send_request: defer
2024-07-26 20:39:46,962 INFO    SenderThread:27472 [sender.py:send_request_defer():610] handle sender defer: 4
2024-07-26 20:39:46,962 INFO    SenderThread:27472 [sender.py:transition_state():614] send defer: 5
2024-07-26 20:39:46,962 DEBUG   HandlerThread:27472 [handler.py:handle_request():146] handle_request: defer
2024-07-26 20:39:46,962 INFO    HandlerThread:27472 [handler.py:handle_request_defer():172] handle defer: 5
2024-07-26 20:39:46,962 DEBUG   SenderThread:27472 [sender.py:send():379] send: summary
2024-07-26 20:39:46,963 INFO    SenderThread:27472 [sender.py:_save_file():1390] saving file wandb-summary.json with policy end
2024-07-26 20:39:46,964 DEBUG   SenderThread:27472 [sender.py:send_request():406] send_request: defer
2024-07-26 20:39:46,964 INFO    SenderThread:27472 [sender.py:send_request_defer():610] handle sender defer: 5
2024-07-26 20:39:46,964 INFO    SenderThread:27472 [sender.py:transition_state():614] send defer: 6
2024-07-26 20:39:46,964 DEBUG   HandlerThread:27472 [handler.py:handle_request():146] handle_request: defer
2024-07-26 20:39:46,964 INFO    HandlerThread:27472 [handler.py:handle_request_defer():172] handle defer: 6
2024-07-26 20:39:46,964 DEBUG   SenderThread:27472 [sender.py:send_request():406] send_request: defer
2024-07-26 20:39:46,964 INFO    SenderThread:27472 [sender.py:send_request_defer():610] handle sender defer: 6
2024-07-26 20:39:46,968 DEBUG   HandlerThread:27472 [handler.py:handle_request():146] handle_request: status_report
2024-07-26 20:39:47,192 INFO    SenderThread:27472 [sender.py:transition_state():614] send defer: 7
2024-07-26 20:39:47,192 DEBUG   HandlerThread:27472 [handler.py:handle_request():146] handle_request: defer
2024-07-26 20:39:47,192 INFO    HandlerThread:27472 [handler.py:handle_request_defer():172] handle defer: 7
2024-07-26 20:39:47,192 DEBUG   SenderThread:27472 [sender.py:send_request():406] send_request: defer
2024-07-26 20:39:47,192 INFO    SenderThread:27472 [sender.py:send_request_defer():610] handle sender defer: 7
2024-07-26 20:39:47,278 INFO    Thread-298:27472 [dir_watcher.py:_on_file_modified():288] file/dir modified: c:\Users\lenovo\Desktop\CUHK\Research\wandb\run-20240726_203859-g677k1a8\files\config.yaml
2024-07-26 20:39:47,278 INFO    Thread-298:27472 [dir_watcher.py:_on_file_created():271] file/dir created: c:\Users\lenovo\Desktop\CUHK\Research\wandb\run-20240726_203859-g677k1a8\files\wandb-summary.json
2024-07-26 20:39:47,656 DEBUG   HandlerThread:27472 [handler.py:handle_request():146] handle_request: status_report
2024-07-26 20:39:47,688 INFO    SenderThread:27472 [sender.py:transition_state():614] send defer: 8
2024-07-26 20:39:47,688 DEBUG   HandlerThread:27472 [handler.py:handle_request():146] handle_request: defer
2024-07-26 20:39:47,688 INFO    HandlerThread:27472 [handler.py:handle_request_defer():172] handle defer: 8
2024-07-26 20:39:47,689 DEBUG   SenderThread:27472 [sender.py:send_request():406] send_request: defer
2024-07-26 20:39:47,689 INFO    SenderThread:27472 [sender.py:send_request_defer():610] handle sender defer: 8
2024-07-26 20:39:47,689 INFO    SenderThread:27472 [job_builder.py:build():318] Attempting to build job artifact
2024-07-26 20:39:47,689 INFO    SenderThread:27472 [job_builder.py:_get_source_type():466] no source found
2024-07-26 20:39:47,690 INFO    SenderThread:27472 [sender.py:transition_state():614] send defer: 9
2024-07-26 20:39:47,690 DEBUG   HandlerThread:27472 [handler.py:handle_request():146] handle_request: defer
2024-07-26 20:39:47,690 INFO    HandlerThread:27472 [handler.py:handle_request_defer():172] handle defer: 9
2024-07-26 20:39:47,690 DEBUG   SenderThread:27472 [sender.py:send_request():406] send_request: defer
2024-07-26 20:39:47,690 INFO    SenderThread:27472 [sender.py:send_request_defer():610] handle sender defer: 9
2024-07-26 20:39:47,690 INFO    SenderThread:27472 [dir_watcher.py:finish():358] shutting down directory watcher
2024-07-26 20:39:47,800 DEBUG   HandlerThread:27472 [handler.py:handle_request():146] handle_request: status_report
2024-07-26 20:39:47,879 DEBUG   HandlerThread:27472 [handler.py:handle_request():146] handle_request: poll_exit
2024-07-26 20:39:48,291 INFO    SenderThread:27472 [dir_watcher.py:_on_file_modified():288] file/dir modified: c:\Users\lenovo\Desktop\CUHK\Research\wandb\run-20240726_203859-g677k1a8\files\output.log
2024-07-26 20:39:48,292 INFO    SenderThread:27472 [dir_watcher.py:finish():388] scan: c:\Users\lenovo\Desktop\CUHK\Research\wandb\run-20240726_203859-g677k1a8\files
2024-07-26 20:39:48,292 INFO    SenderThread:27472 [dir_watcher.py:finish():402] scan save: c:\Users\lenovo\Desktop\CUHK\Research\wandb\run-20240726_203859-g677k1a8\files\conda-environment.yaml conda-environment.yaml
2024-07-26 20:39:48,292 INFO    SenderThread:27472 [dir_watcher.py:finish():402] scan save: c:\Users\lenovo\Desktop\CUHK\Research\wandb\run-20240726_203859-g677k1a8\files\config.yaml config.yaml
2024-07-26 20:39:48,294 INFO    SenderThread:27472 [dir_watcher.py:finish():402] scan save: c:\Users\lenovo\Desktop\CUHK\Research\wandb\run-20240726_203859-g677k1a8\files\output.log output.log
2024-07-26 20:39:48,297 INFO    SenderThread:27472 [dir_watcher.py:finish():402] scan save: c:\Users\lenovo\Desktop\CUHK\Research\wandb\run-20240726_203859-g677k1a8\files\requirements.txt requirements.txt
2024-07-26 20:39:48,300 INFO    SenderThread:27472 [dir_watcher.py:finish():402] scan save: c:\Users\lenovo\Desktop\CUHK\Research\wandb\run-20240726_203859-g677k1a8\files\wandb-metadata.json wandb-metadata.json
2024-07-26 20:39:48,301 INFO    SenderThread:27472 [dir_watcher.py:finish():402] scan save: c:\Users\lenovo\Desktop\CUHK\Research\wandb\run-20240726_203859-g677k1a8\files\wandb-summary.json wandb-summary.json
2024-07-26 20:39:48,303 INFO    SenderThread:27472 [sender.py:transition_state():614] send defer: 10
2024-07-26 20:39:48,303 DEBUG   SenderThread:27472 [sender.py:send_request():406] send_request: poll_exit
2024-07-26 20:39:48,303 DEBUG   HandlerThread:27472 [handler.py:handle_request():146] handle_request: defer
2024-07-26 20:39:48,303 INFO    HandlerThread:27472 [handler.py:handle_request_defer():172] handle defer: 10
2024-07-26 20:39:48,305 DEBUG   SenderThread:27472 [sender.py:send_request():406] send_request: defer
2024-07-26 20:39:48,305 INFO    SenderThread:27472 [sender.py:send_request_defer():610] handle sender defer: 10
2024-07-26 20:39:48,305 INFO    SenderThread:27472 [file_pusher.py:finish():172] shutting down file pusher
2024-07-26 20:39:48,480 ERROR   wandb-upload_1:27472 [internal_api.py:execute():373] 404 response executing GraphQL.
2024-07-26 20:39:48,480 ERROR   wandb-upload_1:27472 [internal_api.py:execute():374] {"errors":[{"message":"run exp/g677k1a8 not found during createRunFiles","path":["createRunFiles"]}],"data":{"createRunFiles":null}}
2024-07-26 20:39:48,481 ERROR   Thread-297:27472 [step_upload.py:_handle_event():200] Failed to upload file: c:\Users\lenovo\Desktop\CUHK\Research\wandb\run-20240726_203859-g677k1a8\files\config.yaml
Traceback (most recent call last):
  File "c:\Users\lenovo\anaconda3\envs\dl\lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "c:\Users\lenovo\anaconda3\envs\dl\lib\site-packages\wandb\sdk\internal\internal_api.py", line 369, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "c:\Users\lenovo\anaconda3\envs\dl\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "c:\Users\lenovo\anaconda3\envs\dl\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "c:\Users\lenovo\anaconda3\envs\dl\lib\site-packages\wandb\sdk\lib\gql_request.py", line 59, in execute
    request.raise_for_status()
  File "c:\Users\lenovo\anaconda3\envs\dl\lib\site-packages\requests\models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\lenovo\anaconda3\envs\dl\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "c:\Users\lenovo\anaconda3\envs\dl\lib\site-packages\wandb\filesync\step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "c:\Users\lenovo\anaconda3\envs\dl\lib\site-packages\wandb\filesync\step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "c:\Users\lenovo\anaconda3\envs\dl\lib\site-packages\wandb\filesync\upload_job.py", line 57, in run
    self.push()
  File "c:\Users\lenovo\anaconda3\envs\dl\lib\site-packages\wandb\filesync\upload_job.py", line 106, in push
    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
  File "c:\Users\lenovo\anaconda3\envs\dl\lib\site-packages\wandb\apis\normalize.py", line 73, in wrapper
    raise err
  File "c:\Users\lenovo\anaconda3\envs\dl\lib\site-packages\wandb\apis\normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\lenovo\anaconda3\envs\dl\lib\site-packages\wandb\sdk\internal\internal_api.py", line 2386, in upload_urls
    query_result = self.gql(
  File "c:\Users\lenovo\anaconda3\envs\dl\lib\site-packages\wandb\sdk\internal\internal_api.py", line 341, in gql
    ret = self._retry_gql(
  File "c:\Users\lenovo\anaconda3\envs\dl\lib\site-packages\wandb\sdk\lib\retry.py", line 147, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
  File "c:\Users\lenovo\anaconda3\envs\dl\lib\site-packages\wandb\util.py", line 910, in no_retry_auth
    raise CommError(
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-07-26 20:39:48,491 ERROR   wandb-upload_0:27472 [internal_api.py:execute():373] 404 response executing GraphQL.
2024-07-26 20:39:48,495 ERROR   wandb-upload_0:27472 [internal_api.py:execute():374] {"errors":[{"message":"run exp/g677k1a8 not found during createRunFiles","path":["createRunFiles"]}],"data":{"createRunFiles":null}}
2024-07-26 20:39:48,496 ERROR   Thread-297:27472 [step_upload.py:_handle_event():200] Failed to upload file: c:\Users\lenovo\Desktop\CUHK\Research\wandb\run-20240726_203859-g677k1a8\files\conda-environment.yaml
Traceback (most recent call last):
  File "c:\Users\lenovo\anaconda3\envs\dl\lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "c:\Users\lenovo\anaconda3\envs\dl\lib\site-packages\wandb\sdk\internal\internal_api.py", line 369, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "c:\Users\lenovo\anaconda3\envs\dl\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "c:\Users\lenovo\anaconda3\envs\dl\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "c:\Users\lenovo\anaconda3\envs\dl\lib\site-packages\wandb\sdk\lib\gql_request.py", line 59, in execute
    request.raise_for_status()
  File "c:\Users\lenovo\anaconda3\envs\dl\lib\site-packages\requests\models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\lenovo\anaconda3\envs\dl\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "c:\Users\lenovo\anaconda3\envs\dl\lib\site-packages\wandb\filesync\step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "c:\Users\lenovo\anaconda3\envs\dl\lib\site-packages\wandb\filesync\step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "c:\Users\lenovo\anaconda3\envs\dl\lib\site-packages\wandb\filesync\upload_job.py", line 57, in run
    self.push()
  File "c:\Users\lenovo\anaconda3\envs\dl\lib\site-packages\wandb\filesync\upload_job.py", line 106, in push
    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
  File "c:\Users\lenovo\anaconda3\envs\dl\lib\site-packages\wandb\apis\normalize.py", line 73, in wrapper
    raise err
  File "c:\Users\lenovo\anaconda3\envs\dl\lib\site-packages\wandb\apis\normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\lenovo\anaconda3\envs\dl\lib\site-packages\wandb\sdk\internal\internal_api.py", line 2386, in upload_urls
    query_result = self.gql(
  File "c:\Users\lenovo\anaconda3\envs\dl\lib\site-packages\wandb\sdk\internal\internal_api.py", line 341, in gql
    ret = self._retry_gql(
  File "c:\Users\lenovo\anaconda3\envs\dl\lib\site-packages\wandb\sdk\lib\retry.py", line 147, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
  File "c:\Users\lenovo\anaconda3\envs\dl\lib\site-packages\wandb\util.py", line 910, in no_retry_auth
    raise CommError(
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-07-26 20:39:48,510 ERROR   wandb-upload_3:27472 [internal_api.py:execute():373] 404 response executing GraphQL.
2024-07-26 20:39:48,510 ERROR   wandb-upload_3:27472 [internal_api.py:execute():374] {"errors":[{"message":"run exp/g677k1a8 not found during createRunFiles","path":["createRunFiles"]}],"data":{"createRunFiles":null}}
2024-07-26 20:39:48,510 ERROR   Thread-297:27472 [step_upload.py:_handle_event():200] Failed to upload file: c:\Users\lenovo\Desktop\CUHK\Research\wandb\run-20240726_203859-g677k1a8\files\requirements.txt
Traceback (most recent call last):
  File "c:\Users\lenovo\anaconda3\envs\dl\lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "c:\Users\lenovo\anaconda3\envs\dl\lib\site-packages\wandb\sdk\internal\internal_api.py", line 369, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "c:\Users\lenovo\anaconda3\envs\dl\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "c:\Users\lenovo\anaconda3\envs\dl\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "c:\Users\lenovo\anaconda3\envs\dl\lib\site-packages\wandb\sdk\lib\gql_request.py", line 59, in execute
    request.raise_for_status()
  File "c:\Users\lenovo\anaconda3\envs\dl\lib\site-packages\requests\models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\lenovo\anaconda3\envs\dl\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "c:\Users\lenovo\anaconda3\envs\dl\lib\site-packages\wandb\filesync\step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "c:\Users\lenovo\anaconda3\envs\dl\lib\site-packages\wandb\filesync\step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "c:\Users\lenovo\anaconda3\envs\dl\lib\site-packages\wandb\filesync\upload_job.py", line 57, in run
    self.push()
  File "c:\Users\lenovo\anaconda3\envs\dl\lib\site-packages\wandb\filesync\upload_job.py", line 106, in push
    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
  File "c:\Users\lenovo\anaconda3\envs\dl\lib\site-packages\wandb\apis\normalize.py", line 73, in wrapper
    raise err
  File "c:\Users\lenovo\anaconda3\envs\dl\lib\site-packages\wandb\apis\normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\lenovo\anaconda3\envs\dl\lib\site-packages\wandb\sdk\internal\internal_api.py", line 2386, in upload_urls
    query_result = self.gql(
  File "c:\Users\lenovo\anaconda3\envs\dl\lib\site-packages\wandb\sdk\internal\internal_api.py", line 341, in gql
    ret = self._retry_gql(
  File "c:\Users\lenovo\anaconda3\envs\dl\lib\site-packages\wandb\sdk\lib\retry.py", line 147, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
  File "c:\Users\lenovo\anaconda3\envs\dl\lib\site-packages\wandb\util.py", line 910, in no_retry_auth
    raise CommError(
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-07-26 20:39:48,517 ERROR   wandb-upload_4:27472 [internal_api.py:execute():373] 404 response executing GraphQL.
2024-07-26 20:39:48,517 ERROR   wandb-upload_4:27472 [internal_api.py:execute():374] {"errors":[{"message":"run exp/g677k1a8 not found during createRunFiles","path":["createRunFiles"]}],"data":{"createRunFiles":null}}
2024-07-26 20:39:48,518 ERROR   Thread-297:27472 [step_upload.py:_handle_event():200] Failed to upload file: c:\Users\lenovo\Desktop\CUHK\Research\wandb\run-20240726_203859-g677k1a8\files\wandb-summary.json
Traceback (most recent call last):
  File "c:\Users\lenovo\anaconda3\envs\dl\lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "c:\Users\lenovo\anaconda3\envs\dl\lib\site-packages\wandb\sdk\internal\internal_api.py", line 369, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "c:\Users\lenovo\anaconda3\envs\dl\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "c:\Users\lenovo\anaconda3\envs\dl\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "c:\Users\lenovo\anaconda3\envs\dl\lib\site-packages\wandb\sdk\lib\gql_request.py", line 59, in execute
    request.raise_for_status()
  File "c:\Users\lenovo\anaconda3\envs\dl\lib\site-packages\requests\models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\lenovo\anaconda3\envs\dl\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "c:\Users\lenovo\anaconda3\envs\dl\lib\site-packages\wandb\filesync\step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "c:\Users\lenovo\anaconda3\envs\dl\lib\site-packages\wandb\filesync\step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "c:\Users\lenovo\anaconda3\envs\dl\lib\site-packages\wandb\filesync\upload_job.py", line 57, in run
    self.push()
  File "c:\Users\lenovo\anaconda3\envs\dl\lib\site-packages\wandb\filesync\upload_job.py", line 106, in push
    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
  File "c:\Users\lenovo\anaconda3\envs\dl\lib\site-packages\wandb\apis\normalize.py", line 73, in wrapper
    raise err
  File "c:\Users\lenovo\anaconda3\envs\dl\lib\site-packages\wandb\apis\normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\lenovo\anaconda3\envs\dl\lib\site-packages\wandb\sdk\internal\internal_api.py", line 2386, in upload_urls
    query_result = self.gql(
  File "c:\Users\lenovo\anaconda3\envs\dl\lib\site-packages\wandb\sdk\internal\internal_api.py", line 341, in gql
    ret = self._retry_gql(
  File "c:\Users\lenovo\anaconda3\envs\dl\lib\site-packages\wandb\sdk\lib\retry.py", line 147, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
  File "c:\Users\lenovo\anaconda3\envs\dl\lib\site-packages\wandb\util.py", line 910, in no_retry_auth
    raise CommError(
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-07-26 20:39:48,540 ERROR   wandb-upload_2:27472 [internal_api.py:execute():373] 404 response executing GraphQL.
2024-07-26 20:39:48,540 ERROR   wandb-upload_2:27472 [internal_api.py:execute():374] {"errors":[{"message":"run exp/g677k1a8 not found during createRunFiles","path":["createRunFiles"]}],"data":{"createRunFiles":null}}
2024-07-26 20:39:48,541 ERROR   Thread-297:27472 [step_upload.py:_handle_event():200] Failed to upload file: c:\Users\lenovo\Desktop\CUHK\Research\wandb\run-20240726_203859-g677k1a8\files\output.log
Traceback (most recent call last):
  File "c:\Users\lenovo\anaconda3\envs\dl\lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "c:\Users\lenovo\anaconda3\envs\dl\lib\site-packages\wandb\sdk\internal\internal_api.py", line 369, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "c:\Users\lenovo\anaconda3\envs\dl\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "c:\Users\lenovo\anaconda3\envs\dl\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "c:\Users\lenovo\anaconda3\envs\dl\lib\site-packages\wandb\sdk\lib\gql_request.py", line 59, in execute
    request.raise_for_status()
  File "c:\Users\lenovo\anaconda3\envs\dl\lib\site-packages\requests\models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\lenovo\anaconda3\envs\dl\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "c:\Users\lenovo\anaconda3\envs\dl\lib\site-packages\wandb\filesync\step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "c:\Users\lenovo\anaconda3\envs\dl\lib\site-packages\wandb\filesync\step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "c:\Users\lenovo\anaconda3\envs\dl\lib\site-packages\wandb\filesync\upload_job.py", line 57, in run
    self.push()
  File "c:\Users\lenovo\anaconda3\envs\dl\lib\site-packages\wandb\filesync\upload_job.py", line 106, in push
    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
  File "c:\Users\lenovo\anaconda3\envs\dl\lib\site-packages\wandb\apis\normalize.py", line 73, in wrapper
    raise err
  File "c:\Users\lenovo\anaconda3\envs\dl\lib\site-packages\wandb\apis\normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\lenovo\anaconda3\envs\dl\lib\site-packages\wandb\sdk\internal\internal_api.py", line 2386, in upload_urls
    query_result = self.gql(
  File "c:\Users\lenovo\anaconda3\envs\dl\lib\site-packages\wandb\sdk\internal\internal_api.py", line 341, in gql
    ret = self._retry_gql(
  File "c:\Users\lenovo\anaconda3\envs\dl\lib\site-packages\wandb\sdk\lib\retry.py", line 147, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
  File "c:\Users\lenovo\anaconda3\envs\dl\lib\site-packages\wandb\util.py", line 910, in no_retry_auth
    raise CommError(
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-07-26 20:39:48,747 INFO    Thread-297:27472 [sender.py:transition_state():614] send defer: 11
2024-07-26 20:39:48,747 DEBUG   HandlerThread:27472 [handler.py:handle_request():146] handle_request: defer
2024-07-26 20:39:48,747 INFO    HandlerThread:27472 [handler.py:handle_request_defer():172] handle defer: 11
2024-07-26 20:39:48,747 DEBUG   SenderThread:27472 [sender.py:send_request():406] send_request: defer
2024-07-26 20:39:48,747 INFO    SenderThread:27472 [sender.py:send_request_defer():610] handle sender defer: 11
2024-07-26 20:39:48,748 INFO    SenderThread:27472 [file_pusher.py:join():178] waiting for file pusher
2024-07-26 20:39:48,748 INFO    SenderThread:27472 [sender.py:transition_state():614] send defer: 12
2024-07-26 20:39:48,748 DEBUG   HandlerThread:27472 [handler.py:handle_request():146] handle_request: defer
2024-07-26 20:39:48,748 INFO    HandlerThread:27472 [handler.py:handle_request_defer():172] handle defer: 12
2024-07-26 20:39:48,748 DEBUG   SenderThread:27472 [sender.py:send_request():406] send_request: defer
2024-07-26 20:39:48,748 INFO    SenderThread:27472 [sender.py:send_request_defer():610] handle sender defer: 12
2024-07-26 20:39:48,748 INFO    SenderThread:27472 [file_stream.py:finish():614] file stream finish called
2024-07-26 20:39:48,890 DEBUG   HandlerThread:27472 [handler.py:handle_request():146] handle_request: poll_exit
2024-07-26 20:39:48,951 ERROR   FileStreamThread:27472 [file_stream.py:_handle_response():523] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/hokfong-the-chinese-university-of-hong-kong/exp/g677k1a8/file_stream
NoneType: None
2024-07-26 20:39:49,142 INFO    SenderThread:27472 [file_stream.py:finish():618] file stream finish is done
2024-07-26 20:39:49,142 INFO    SenderThread:27472 [sender.py:transition_state():614] send defer: 13
2024-07-26 20:39:49,142 DEBUG   SenderThread:27472 [sender.py:send_request():406] send_request: poll_exit
2024-07-26 20:39:49,142 DEBUG   HandlerThread:27472 [handler.py:handle_request():146] handle_request: defer
2024-07-26 20:39:49,143 INFO    HandlerThread:27472 [handler.py:handle_request_defer():172] handle defer: 13
2024-07-26 20:39:49,143 DEBUG   SenderThread:27472 [sender.py:send_request():406] send_request: defer
2024-07-26 20:39:49,143 INFO    SenderThread:27472 [sender.py:send_request_defer():610] handle sender defer: 13
2024-07-26 20:39:49,143 INFO    SenderThread:27472 [sender.py:transition_state():614] send defer: 14
2024-07-26 20:39:49,143 DEBUG   HandlerThread:27472 [handler.py:handle_request():146] handle_request: defer
2024-07-26 20:39:49,143 DEBUG   SenderThread:27472 [sender.py:send():379] send: final
2024-07-26 20:39:49,144 INFO    HandlerThread:27472 [handler.py:handle_request_defer():172] handle defer: 14
2024-07-26 20:39:49,144 DEBUG   SenderThread:27472 [sender.py:send():379] send: footer
2024-07-26 20:39:49,144 DEBUG   SenderThread:27472 [sender.py:send_request():406] send_request: defer
2024-07-26 20:39:49,144 INFO    SenderThread:27472 [sender.py:send_request_defer():610] handle sender defer: 14
2024-07-26 20:39:49,145 DEBUG   HandlerThread:27472 [handler.py:handle_request():146] handle_request: poll_exit
2024-07-26 20:39:49,145 DEBUG   SenderThread:27472 [sender.py:send_request():406] send_request: poll_exit
2024-07-26 20:39:49,146 DEBUG   HandlerThread:27472 [handler.py:handle_request():146] handle_request: internal_messages
2024-07-26 20:39:49,147 DEBUG   HandlerThread:27472 [handler.py:handle_request():146] handle_request: server_info
2024-07-26 20:39:49,147 DEBUG   HandlerThread:27472 [handler.py:handle_request():146] handle_request: get_summary
2024-07-26 20:39:49,147 DEBUG   HandlerThread:27472 [handler.py:handle_request():146] handle_request: sampled_history
2024-07-26 20:39:49,147 DEBUG   SenderThread:27472 [sender.py:send_request():406] send_request: server_info
2024-07-26 20:39:49,332 DEBUG   HandlerThread:27472 [handler.py:handle_request():146] handle_request: shutdown
2024-07-26 20:39:49,332 INFO    HandlerThread:27472 [handler.py:finish():866] shutting down handler
2024-07-26 20:39:50,150 INFO    WriterThread:27472 [datastore.py:close():296] close: c:\Users\lenovo\Desktop\CUHK\Research\wandb\run-20240726_203859-g677k1a8\run-g677k1a8.wandb
2024-07-26 20:39:50,341 INFO    SenderThread:27472 [sender.py:finish():1546] shutting down sender
2024-07-26 20:39:50,341 INFO    SenderThread:27472 [file_pusher.py:finish():172] shutting down file pusher
2024-07-26 20:39:50,341 INFO    SenderThread:27472 [file_pusher.py:join():178] waiting for file pusher
